apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
      - name: ms2container
        image: hamzahajjou/ms2
        ports:
        - containerPort: 4000    
---
apiVersion: v1
kind: Service
metadata:
  name: ms2-service
  labels:
    app: ms2-service
spec:
  ports:
  - port: 4000
    name: http
    targetPort: 4000
  selector:
    app: ms2