apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiservice
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uiservice
  template:
    metadata:
      labels:
        app: uiservice
    spec:
      containers:
        - name: service
          image: mouliehatim/uiservice
          ports:
            - containerPort: 3000
          # env:
          #   - name: PORT
          #     value: "9555"
---
apiVersion: v1
kind: Service
metadata:
  name: uiservice
  namespace: production
spec:
  selector:
    app: uiservice
  ports:
    - port: 3000
      targetPort: 3000
