stages:
  - test
  - build
  - deploy
  - k8s

variables:
  BACKEND_APP_NAME: auth-image
  FRONTEND_APP_NAME: ui-image
  BACKEND_CI_REGISTRY_IMAGE: prankster08/$BACKEND_APP_NAME
  FRONTEND_CI_REGISTRY_IMAGE: prankster08/$FRONTEND_APP_NAME
  CD_CHART_REPO: Game-Streaming
  CD_GIT_REPOSITORY: git@gitlab.com:abdelmoghit.idhsaine/$CD_CHART_REPO.git
  CD_MANIFEST_FILE: Chart.yaml
  TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA




    
image: docker:latest 
services:
  - name: docker:dind

before_script:
  - echo $BACKEND_CI_REGISTRY_IMAGE:$TAG $PWD
  - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin

after_script:
  - docker image prune -af 

test_auth:
  stage: test
  image: node:14-alpine
  before_script:
    - cd Auth-service
    - npm i
  script:
    # - cd Auth-service
    - npm test
    - cd ..

build_backend_image:
  stage: build
  script:
    - cd Auth-service
    - cat Dockerfile
    - docker build --tag $BACKEND_CI_REGISTRY_IMAGE:$TAG .
    - docker push $BACKEND_CI_REGISTRY_IMAGE:$TAG

build_frontend_image:
  stage: build
  script:
    - cd Front-end
    - cat Dockerfile
    - docker build --tag $FRONTEND_CI_REGISTRY_IMAGE:$TAG .
    - docker push $FRONTEND_CI_REGISTRY_IMAGE:$TAG

tag_latest_image:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $BACKEND_CI_REGISTRY_IMAGE:$TAG
    - docker tag $BACKEND_CI_REGISTRY_IMAGE:$TAG $BACKEND_CI_REGISTRY_IMAGE:latest
    - docker push $BACKEND_CI_REGISTRY_IMAGE:latest
    - docker pull $FRONTEND_CI_REGISTRY_IMAGE:$TAG
    - docker tag $FRONTEND_CI_REGISTRY_IMAGE:$TAG $FRONTEND_CI_REGISTRY_IMAGE:latest
    - docker push $FRONTEND_CI_REGISTRY_IMAGE:latest


update:
  stage: k8s
  before_script:
    - apt-get update -y && apt-get install -yqqf openssh-client git unzip sshpass rsync --fix-missing
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apk add git
    - git config --global user.email "$CI_EMAIL"
    - git config --global user.name "$CI_USERNAME"
  script:
    - echo 'test file'
    # - export TAG=abdelmoghit-39a61491
    - ssh -T git@gitlab.com
    - cd ..
    - git clone git@gitlab.com:abdelmoghit.idhsaine/Game-Streaming-Deployment.git
    - ls
    - cd Game-Streaming-Deployment/development/k8s-services/
    #test these in the ui first
    - echo llllllllllllllllll
    - cat ui-service.yaml
    - sed -i "s/ui-image:.*/ui-image:$TAG/g" ui-service.yaml
    - cat ui-service.yaml
    - echo llllllllllllllllll
    - cat auth-service.yaml
    - sed -i "s/auth-image:.*/auth-image:$TAG/g" auth-service.yaml
    - cat auth-service.yaml
    - echo llllllllllllllllll
    - git add -A
    - git commit -m "test push gitlab"
    - git push   

