apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consermer
  namespace: production
  annotations:
    kubernetes.io/ingress.class: kong
username: consermer
credentials:
  - consermer-credentials